[package]
name = "mnk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
named_pipe = "0.4.1"
rdev = "0.5.3"
serde_json = "1.0.111"
